print("Hello World!")
png("C:\\Users\\vikas\\Dropbox\\CS6200_V_Sangwan\\HW5\\output\\HW1\\150903.png", width=10, height=10, units="in", res=300)
Recall <- read.csv(file="C:\\Users\\vikas\\Dropbox\\CS6200_V_Sangwan\\HW5\\output\\HW1\\150903.csv",sep=",",head=TRUE)
Precision <- read.csv(file="C:\\Users\\vikas\\Dropbox\\CS6200_V_Sangwan\\HW5\\output\\HW1\\150903.csv",sep=",",head=TRUE)
plot(Recall$Recall, Precision$Precision, type="o", col="blue")
dev.off()